/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HomNAND_EFastCircuit */

#ifndef _Included_HomNAND_EFastCircuit
#define _Included_HomNAND_EFastCircuit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HomNAND_EFastCircuit
 * Method:    feval
 * Signature: ([Z)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_HomNAND_EFastCircuit_feval
  (JNIEnv *, jobject, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
